### ISSUE TITLE
Check line 150

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [TwoThreeTwo/RandomStringGenerator#1]
So, the if statement is linked to 1 else statement except that one else statement is not linked to the right one meaning if I may have to rewrite it, after school come check that section and identify the issue. I've been going insane...

**Comment by Four44Four** [comment]
insane in the membrane

**Comment by Four44Four** [comment]
the restroom smells like smt's burning and i think it could be weed

**Comment by Four44Four** [comment]
am i stoned

**Comment by Four44Four** [comment]
also plz organize ur code better i still dont understand anything

**Comment by Four44Four** [comment]
or maybe im just stoned

**Comment by Four44Four** [comment]
bro why tf are there 2 else statements linked to each other on lines 153 && 187

**Comment by Four44Four** [comment]
[fixedSpgehtticodeQuestionmark.txt](https://github.com/TwoThreeTwo/RandomStringGenerator/files/8766322/fixedSpgehtticodeQuestionmark.txt)

**Comment by Tarkan-Zarrouk** [comment]
1: why do you have customFileExit as your var, keep it at 1 letter with 1 number, it's easier, 
2: why do you have brackets that go after the method 
ie: int isCustomFileExt = JOptionPane.showConfirmDialog(null, "Would you like a custom file extension?", "Password Generator", JOptionPane.YES_NO_OPTION);	
	if (isCustomFileExt == JOptionPane.YES_OPTION)
	{
3:I'll test it rn, but it looks not reliable

**Comment by Tarkan-Zarrouk** [comment]
make proper code because I have to move a lot of shit around to bring it into scope :/

**Comment by Tarkan-Zarrouk** [comment]
if (Objects.equals(fileExtension, "")) {
instead of 
		if (fileExtension == "")

**Comment by Tarkan-Zarrouk** [comment]
your 'file' fucked up the entire process between the start point and endpoint, you basically made everything that doesn't include EnterCustomFileExtension and NotGeneratingFile gone. I'm going to relook at it because the one I created actually worked it's just that when you enter a custom file extension, it still checks for the file that exists with it resulting in a null error.

**Comment by Tarkan-Zarrouk** [comment]
Seems like I found the issue for this

**Comment by Tarkan-Zarrouk** [comment]
Basically, on the event where a user inputs a custom file output, it acts like that you wanted to cancel it meaning if I believe I messed something up between the point where I created the customUserInputDialog and the canceling showMessageDialog.

**Comment by Tarkan-Zarrouk** [comment]
This issue has been resolved.
